hospital/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hospital import views

urlpatterns = [
    url(r'^home/(?P<slug>.+)$', views.HospitalHome.as_view(), name='overview'),
    url(r'^appointments/approve/(?P<id>.+)$', login_required(views.AppointmentApprove.as_view()),
        name='appointment-approve'),
    url(r'^appointments/reject/(?P<id>.+)$', login_required(views.AppointmentReject.as_view()),
        name='appointment-reject'),
    url(r'^doctors/(?P<slug>.+)$', views.DoctorHome.as_view(), name='doctor-home'),
    url(r'^appoint/doctor/(?P<slug>.+)$', views.appoint_doctor, name='appoint-doctor'),
    url(r'^list/$', views.HospitalsAll.as_view(), name='list-hospitals'),
]

medtour/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
import landing.views
from hospital import views

admin.autodiscover()

urlpatterns = [
    url(r'^home$', login_required(landing.views.HomeView.as_view()), name='home'),
    url(r'^signup/$', landing.views.signup, name='signup'),
    url(r'^account/overview/$', login_required(landing.views.AccountOverview.as_view()), name='overview'),
    url(r'^settings/password/$', login_required(landing.views.PasswordChangeView.as_view()), name='password'),
    url(r'^settings/username/$', login_required(landing.views.ChangeUsername.as_view()), name='username'),
    path('admin/', admin.site.urls),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^hospital/', include(('hospital.urls', 'hospital'), namespace='hospital')),
    path('', include('pwa.urls')),
    path('ajax/load-states/', landing.views.load_state, name='ajax_load_states'),
    path('ajax/load-cities/', landing.views.load_city, name='ajax_load_cities'),
    path('ajax/autocomplete/', landing.views.autocomplete, name='ajax_autocomplete'),
    url(r'^$', views.HospitalsAll.as_view(), name='land'),
    url(r'^account_activation_sent/$', landing.views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        landing.views.activate, name='activate'),
    url(r'^edit/hospital/profile/$', login_required(landing.views.CompleteHospitalProfile.as_view()),
        name='complete_hospital_profile'),
]

landing/models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from cities_light.abstract_models import (AbstractCity, AbstractRegion, AbstractCountry)
from cities_light.receivers import connect_default_signals


class Country(AbstractCountry):
    pass


connect_default_signals(Country)


class Region(AbstractRegion):
    pass


connect_default_signals(Region)


class City(AbstractCity):
    timezone = models.CharField(max_length=40)


connect_default_signals(City)


class Profile(models.Model):
    class Meta:
        ordering = ('user',)
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other'),
        ('n', 'Not Specified')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(blank=True, null=True, help_text='Your date of birth')
    gender = models.CharField(max_length=9, choices=GENDER_CHOICES, blank=True, null=True)
    mail_notifications_allowed = models.BooleanField(default=True,
                                                     help_text='Get all your notifications via mail')
    newsletter = models.BooleanField(default=True, help_text='Get notifications our new services and features')
    use_gravtar = models.BooleanField(default=False, help_text='One avatar to rule them all!')
    beta_user = models.BooleanField(default=False, help_text='Test and help us find bugs in our unreleased features')
    avatar = models.URLField(null=True, blank=True, help_text='Profile picture URL')
    avatar_small = models.URLField(null=True, blank=True, help_text='Profile picture smaller URL')
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.PROTECT)
    state = models.ForeignKey(Region, null=True, blank=True, on_delete=models.PROTECT)
    city = models.ForeignKey(City, null=True, blank=True, on_delete=models.PROTECT)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

    def get_fullname(self):
        full_name = '%s %s' % (self.user.first_name, self.user.last_name)
        return full_name.strip()

    def get_age(self):
        today = date.today()
        if self.dob:
            return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

landing/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from social_django.models import UserSocialAuth
from hospital.models import Doctor, Appointment, Hospital
from hospital.views import HospitalsAll
from hospital.forms import InviteDocForm
from landing.models import Region, City, Profile
from landing.tokens import account_activation_token
from .forms import ProfileForm, UsernameForm, SignUpForm, HospitalForm
from medtour import settings
from landing.utils import sg_mail


def land(request):
    return render(request, 'landing/base.html')


class CompleteHospitalProfile(View):
    def get(self, request):
        form = HospitalForm(instance=request.user.hospital)
        return render(request, 'landing/hospital_profile_complete.html', {'form': form})

    def post(self, request):
        form = HospitalForm(request.POST, instance=request.user.hospital)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('home')
        else:
            messages.error(
                request, 'Slug is already taken, please try another one.')
            return render(request, 'landing/hospital_profile_complete.html', {'form': form})


class ChangeUsername(View):
    def get(self, request):
        form = UsernameForm(instance=request.user)
        return render(request, 'landing/username.html', {'form': form})

    def post(self, request):
        form = UsernameForm(request.POST, request.user)
        if form.is_valid():
            form = UsernameForm(request.POST, instance=request.user)
            form.save()
            messages.success(
                request, 'Your username was successfully updated!')
            update_session_auth_hash(request, request.user)
            return redirect('username')
        else:
            messages.error(
                request, 'Username is already taken, please try another one.')
        return render(request, 'landing/username.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        hospital = Hospital(user=user, email=user.email,
                            name=user.first_name, slug=user.username).save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('complete_hospital_profile')
    else:
        return HospitalsAll.as_view()(request, message=settings.INVALID_ACTIVATION_STRING)


def account_activation_sent(request):
    return render(request, 'registration/account_activation_sent.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MedTour Account'
            from_email = settings.EMAIL_HOST_USER
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            plain_msg = strip_tags(message)
            send_mail(subject, plain_msg, from_email, [
                      user.email], html_message=message, fail_silently=True)
            response = HospitalsAll.as_view()(request, good_message=settings.EMAIL_SENT_STRING)
            return response
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


class HomeView(View):
    def get(self, request, message=None, good_message=None):
        doctors = None
        hospital_appointments = None
        try:
            if request.user.hospital:
                if not request.user.hospital.user.profile.city:
                    message = "Please add city to your profile, for better visibility on platform."
                hospital = request.user.hospital
                doctors = Doctor.objects.filter(hospital=hospital)
                hospital_appointments = Appointment.objects.filter(
                    doctor__in=doctors)
                form = InviteDocForm(request.POST or None)
                return render(request, 'landing/home.html', {'doctors': doctors,
                                                             'happs': hospital_appointments,
                                                             'form': form,
                                                             'message': message,
                                                             'good_message': good_message
                                                             })
        except Hospital.DoesNotExist:
            pass
        try:
            if request.user.doctor:
                slug = request.user.doctor.slug
                doctor = Doctor.objects.get(slug=slug)
                doc_appointments = Appointment.objects.filter(
                    doctor=doctor)
                return render(request, 'landing/doc_home.html', {'happs': doc_appointments, 'message': message,
                                                                 'good_message': good_message})
        except Doctor.DoesNotExist:
            pass
        patient_appointments = Appointment.objects.filter(
            patient__user=request.user) or None
        return render(request, 'landing/patient_home.html', {'doctors': doctors,
                                                             'happs': hospital_appointments,
                                                             'papps': patient_appointments,
                                                             'message': message,
                                                             'good_message': good_message
                                                             })

    def post(self, request, message=None, good_message=None):
        form = InviteDocForm(request.POST or None)
        if form.is_valid():
            doctor = form.save(commit=False)
            doctor.hospital = Hospital.objects.get(
                slug=request.user.hospital.slug)
            doctor.slug = doctor.user.username
            form.save()
            return redirect('home')
        return render(request, 'landing/home.html', {'form': form, 'message': message,
                                                     'good_message': good_message})


# only4 testing
def test_func():
    return True


class AccountOverview(View):
    def get(self, request):
        user = request.user

        try:
            google_login = user.social_auth.get(provider='google-oauth2')
        except UserSocialAuth.DoesNotExist:
            google_login = None

        try:
            twitter_login = user.social_auth.get(provider='twitter')
        except UserSocialAuth.DoesNotExist:
            twitter_login = None

        try:
            facebook_login = user.social_auth.get(provider='facebook')
        except UserSocialAuth.DoesNotExist:
            facebook_login = None

        can_disconnect = (user.social_auth.count() >
                          1 or user.has_usable_password())
        form = ProfileForm(instance=request.user.profile)
        return render(request, 'landing/profile.html', {
            'twitter_login': twitter_login,
            'facebook_login': facebook_login,
            'google_login': google_login,
            'user': user,
            'form': form,
            'can_disconnect': can_disconnect
        })

    def post(self, request):
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('overview')
        else:
            messages.error(request, 'Please correct the error below.')


class PasswordChangeView(View):
    def get(self, request):
        if request.user.has_usable_password():
            password_form = PasswordChangeForm
        else:
            password_form = AdminPasswordChangeForm
        form = password_form(request.user)
        return render(request, 'landing/password.html', {'form': form})

    def post(self, request):
        if request.user.has_usable_password():
            password_form = PasswordChangeForm
        else:
            password_form = AdminPasswordChangeForm

        if request.method == 'POST':
            form = password_form(request.user, request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(
                    request, 'Your password was successfully updated!')
                return redirect('password')
            else:

landing/templates/landing/doc_home.html
{% extends 'landing/base.html' %}
{% load static %}
{% block title %}
    {% if user.hospital %}
        Dashboard | {{ user.doctor.name }}
    {% else %}
        MedTour | Home
    {% endif %}
{% endblock %}
{% block body %}
    <div class="uk-container">
        <h2 class="uk-padding-small uk-text-center uk-text-bold">Dashboard</h2>
        {% if user.doctor %}
            <h3 class="uk-text-lead uk-text-bold uk-text-center">{{ user.doctor.name }}</h3>
            <div class="uk-text-center" id="details-hospital">
                {% if user.doctor.phone_number %}
                    <p><a href="tel:{{ user.doctor.phone_number }}" class="uk-icon-button" uk-icon="receiver"></a> {{ user.doctor.phone_number }}</p>
                {% endif %}

                {% if user.doctor.email %}
                    <p><a href="mailto:{{ user.doctor.email }}" class="uk-icon-button" uk-icon="mail"></a> {{ user.doctor.email }}</p>
                {% endif %}
            </div>
            <div class="uk-width-1-1 uk-child-width-1-1@m uk-margin-remove" uk-grid="masonry: true">
                <div class="uk-card uk-card-hover uk-margin-small-top uk-card-default uk-card-body">
                    <h3 class="uk-card-title uk-button-text uk-text-bold">
                        My Appointments
                    </h3>
                    <table class="uk-table uk-table-responsive uk-table-hover uk-table-divider">
                        <thead>
                            <tr>
                                <th>Patient</th>
                                <th>Remark</th>
                                <th>Time</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for happ in happs %}
                            <tr style="cursor: pointer" href="#appointment-modal-{{ happ.id }}" uk-toggle>
                                <td>
                                    {% if happ.patient.user.profile.avatar %}
                                        <img src="{{ happ.patient.user.profile.avatar_small }}" class="uk-border-circle" width="30" height="30">
                                    {% elif user.hospital %}
                                        <img src="{% static 'images/hospital-default-avtar.png' %}" class="uk-border-circle" width="30" height="30">
                                    {% else %}
                                        {% if happ.patient.user.profile.gender == 'f' %}
                                            <img src="{% static 'images/female.png' %}" class="uk-border-circle" width="30" height="30">
                                        {% else %}
                                            <img src="{% static 'images/anon.png' %}" class="uk-border-circle" width="30" height="30">
                                        {% endif %}
                                    {% endif %}
                                    <span> </span>
                                    <a class="uk-text-bold uk-button uk-button-text">{{ happ.patient.user.first_name }}</a>
                                </td>
                                <td>{{ happ.patients_remarks }}</td>
                                <td>
                                    {% if happ.start_date or happ.end_date %}
                                        {{ happ.start_date }} to {{ happ.end_date }}
                                    {% else %}
                                        Not Available
                                    {% endif %}
                                </td>
                                <td>
                                    {% if happ.rejected %}
                                        <span class="uk-badge uk-label-danger uk-padding-small">Rejected</span>
                                    {% elif not happ.approved %}
                                        <span class="uk-badge uk-label-warning uk-padding-small">Pending</span>
                                    {% else %}
                                        <span class="uk-badge uk-label-success uk-padding-small">Approved</span>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        {% for happ in happs %}
            <div id="appointment-modal-{{ happ.id }}" uk-modal>
                <div class="uk-modal-dialog">
                    <button class="uk-modal-close-default" type="button" uk-close></button>
                    <div class="uk-modal-header">
                        <h2 class="uk-modal-title">Appointment Description</h2>
                    </div>
                    <div class="uk-modal-body">
                        <h3 class="uk-text-meta">Age: {{ happ.patient.user.profile.get_age }} Sex: {{ happ.patient.user.profile.get_gender_display }}</h3>
                        <p>{{ happ.patients_remarks }}</p>
                        <br>
                        Current Status :
                        {% if happ.approved %}
                            <span class="uk-badge uk-label-success uk-padding-small">Approved</span>
                        {% elif happ.rejected %}
                            <span class="uk-badge uk-label-danger uk-padding-small">Rejected</span>
                        {% else %}
                            <span class="uk-badge uk-label-warning uk-padding-small">Pending</span>
                        {% endif %}
                    </div>
                    <div class="uk-modal-footer uk-text-center">
                        <button class="uk-button uk-border-pill uk-margin-right uk-button-danger" onclick="editAppointment('{% url 'hospital:appointment-reject' happ.id %}')" type="button">Reject</button>
                        <button class="uk-button uk-border-pill uk-button-primary" onclick="editAppointment('{% url 'hospital:appointment-approve' happ.id %}')" type="button">Approve</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script>
        function editAppointment(url) {
            window.location = window.location.origin + url;
        }
    </script>
{% endblock %}

landing/templates/landing/hospital_profile_complete.html
{% extends 'landing/base.html' %}
{% block title %}
    Complete Hospital Profile
{% endblock %}
{% block body %}
    <div class="uk-container uk-margin-medium-top">
        <form class="uk-table-responsive uk-align-center uk-border-rounded uk-width-1-2@m uk-box-shadow-large uk-padding-small" action="#" method="post">
            <h2 class="uk-text-success uk-text-center">Complete your Hospital Profile</h2>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <h5 {% if message.tags %}
                        {% if message.tags == "error" %}
                            class="uk-text-danger uk-text-center"
                        {% else %}
                            class="uk-text-{{ message.tags }}"
                        {% endif %}
                    {% endif %}>{{ message }}</h5>
                {% endfor %}
            {% endif %}

            {% csrf_token %}
            <table class="uk-table">
                <thead>
                    <tr>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="uk-text-bold">{{ form.name.label }}</td>
                        <td>{{ form.name }}</td>
                    </tr>
                    <tr>
                        <td class="uk-text-bold">{{ form.address.label }}</td>
                        <td>{{ form.address }}</td>
                    </tr>
                    <tr>
                        <td class="uk-text-bold">{{ form.slug.label }}</td>
                        <td>{{ form.slug }}</td>
                    </tr>
                    <tr>
                        <td class="uk-text-bold">{{ form.phone_number.label }}</td>
                        <td>{{ form.phone_number }}</td>
                    </tr>
                    <tr>
                        <td class="uk-text-bold">{{ form.specialisation.label }}</td>
                        <td>{{ form.specialisation }}</td>
                    </tr>
                </tbody>
            </table>
            <p class="uk-align-center uk-text-center">
                <input class="uk-button uk-button-primary uk-border-pill" type="submit" value="Update" />
                <input class="uk-button uk-button-danger uk-margin-left uk-border-pill" type="reset" value="Clear all changes"/>
            </p>
        </form>
    </div>
{% endblock %}

landing/templates/landing/password.html
{% extends 'landing/base.html' %}
{% block title %}
    Password Settings
{% endblock %}
{% block body %}
  <h2 class="uk-text-bold uk-text-center uk-padding-small">Set/Reset Password</h2>
    <div class="uk-card uk-card-default uk-width-1-2@m uk-text-center uk-card-body uk-align-center uk-margin-medium-top uk-margin-auto-bottom">
        <p class="uk-text-primary uk-text-bold">Your username: {{ user.username }}</p>
        {% if not user.has_usable_password %}
            <p class="uk-text-danger uk-text-bold">You have not defined a password yet.</p>
            <form method="post">
                {% csrf_token %}
                <div class="uk-margin">
                    <div class="uk-inline">
                        <label for="id_password1" class="uk-form-icon" uk-icon="icon: lock"></label>
                        <input class="uk-input" type="password" name="password1" required="" id="id_password1" placeholder="New Password" autofocus="">
                    </div>
                </div>

                <div class="uk-margin">
                    <div class="uk-inline">
                        <label for="id_password2" class="uk-form-icon" uk-icon="icon: lock"></label>
                        <input class="uk-input" type="password" name="password2" required="" placeholder="Confirm Password" id="id_password2" autofocus="">
                    </div>
                </div>
                {% for error_message in form.errors.items %}
                    <div class="uk-text-danger uk-text-bold uk-margin-small-bottom">
                        {{ error_message|striptags }}
                    </div>
                {% endfor %}
                <button class="uk-button uk-button-danger uk-border-pill" type="submit">Set Password</button>
            </form>

        {% else %}
            <p class="uk-text-bold">Enter your new password and click save changes.</p>
            <form method="post">
                {% csrf_token %}
                <div class="uk-margin">
                    <div class="uk-inline">
                        <label for="id_old_password" class="uk-form-icon" uk-icon="icon: lock"></label>
                        <input class="uk-input uk-form-width-large" type="password" name="old_password" autofocus="" id="id_old_password" placeholder="Old Password" required="">
                    </div>
                    {% if form.old_password.errors %}
                        <div class="uk-text-danger uk-text-bold uk-margin-small-bottom uk-margin-small-top uk-list">
                            {{ form.old_password.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="uk-margin">
                    <div class="uk-inline">
                        <label for="id_new_password1" class="uk-form-icon" uk-icon="icon: lock"></label>
                        <input class="uk-input uk-form-width-large" type="password" name="new_password1" autofocus="" id="id_new_password1" placeholder="New Password" required="">
                    </div>
                    {% if form.new_password.errors %}
                        <div class="uk-text-danger uk-text-bold uk-margin-small-bottom uk-margin-small-top uk-list">
                            {{ form.new_password.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="uk-margin">
                    <div class="uk-inline">
                        <label for="id_new_password2" class="uk-form-icon" uk-icon="icon: lock"></label>
                        <input class="uk-input uk-form-width-large" type="password" name="new_password2" required="" placeholder="Confirm Password" id="id_new_password2">
                    </div>
                    {% if form.new_password2.errors %}
                        <div class="uk-text-danger uk-text-bold uk-margin-small-bottom uk-margin-small-top uk-list">
                            {{ form.new_password2.errors }}
                        </div>
                    {% endif %}
                </div>
                <button class="uk-button uk-button-danger uk-border-pill" type="submit">Save changes</button>
            </form>
        {% endif %}
        <hr>
        <span class="uk-text-bold">Need help</span>
        <a class="uk-icon-button uk-button-link" href="#help-password" uk-toggle uk-icon="question"></a>

        <div id="help-password" uk-modal>
            <div class="uk-modal-dialog">

                <div class="uk-modal-header">
                    <h2 class="uk-modal-title">Need help choosing a password?</h2>
                </div>

                <div class="uk-modal-body" uk-overflow-auto>
                    {% for field in form %}
                        <div class="uk-text-bold uk-margin-small-bottom">
                            {% if field.help_text %}
                                <p>{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>

                <div class="uk-modal-footer uk-text-right">
                    <button class="uk-button uk-button-secondary uk-modal-close uk-border-pill" type="button">Got it!</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}