hospital/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hospital import views

urlpatterns = [
    url(r'^home/(?P<slug>.+)$', views.HospitalHome.as_view(), name='overview'),
    url(r'^appointments/approve/(?P<id>.+)$', login_required(views.AppointmentApprove.as_view()),
        name='appointment-approve'),
    url(r'^appointments/reject/(?P<id>.+)$', login_required(views.AppointmentReject.as_view()),
        name='appointment-reject'),
    url(r'^doctors/(?P<slug>.+)$', views.DoctorHome.as_view(), name='doctor-home'),
    url(r'^appoint/doctor/(?P<slug>.+)$', views.appoint_doctor, name='appoint-doctor'),
    url(r'^list/$', views.HospitalsAll.as_view(), name='list-hospitals'),
]

medtour/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
import landing.views
from hospital import views

admin.autodiscover()

urlpatterns = [
    url(r'^home$', login_required(landing.views.HomeView.as_view()), name='home'),
    url(r'^signup/$', landing.views.signup, name='signup'),
    url(r'^account/overview/$', login_required(landing.views.AccountOverview.as_view()), name='overview'),
    url(r'^settings/password/$', login_required(landing.views.PasswordChangeView.as_view()), name='password'),
    url(r'^settings/username/$', login_required(landing.views.ChangeUsername.as_view()), name='username'),
    path('admin/', admin.site.urls),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^hospital/', include(('hospital.urls', 'hospital'), namespace='hospital')),
    path('', include('pwa.urls')),
    path('ajax/load-states/', landing.views.load_state, name='ajax_load_states'),
    path('ajax/load-cities/', landing.views.load_city, name='ajax_load_cities'),
    path('ajax/autocomplete/', landing.views.autocomplete, name='ajax_autocomplete'),
    url(r'^$', views.HospitalsAll.as_view(), name='land'),
    url(r'^account_activation_sent/$', landing.views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        landing.views.activate, name='activate'),
    url(r'^edit/hospital/profile/$', login_required(landing.views.CompleteHospitalProfile.as_view()),
        name='complete_hospital_profile'),
]

hospital/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator

from landing.models import Profile


class Specialisation(models.Model):
    class Meta:
        ordering = ('id',)
        verbose_name = 'specialisation'
        verbose_name_plural = 'specialisations'

    id = models.CharField(unique=True, default=uuid.uuid4,
                          editable=False, max_length=50, primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Hospital(models.Model):
    class Meta:
        ordering = ('-rating',)
        verbose_name = 'Hospital'
        verbose_name_plural = 'Hospitals'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000, null=True, blank=True)
    address = models.TextField(max_length=5000, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    rating = models.PositiveSmallIntegerField(default=3, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format:"
                                         " '+919999999999'.")
    email = models.EmailField(blank=True, help_text="Please enter valid email address, it will be used for "
                                                    "verification.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True, help_text="Please enter "
                                                                                                   "valid phone "
                                                                                                   "number.")
    specialisation = models.ManyToManyField(
        Specialisation, related_name='speciality_of_hospital')
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

    def get_url(self):
        return reverse('hospital:overview', args=[self.slug])

    def get_all_spec(self):
        specs = ""
        for spec in self.specialisation.all():
            specs += spec.name + ", "
        return specs[:-2]


class Doctor(models.Model):
    class Meta:
        ordering = ('name',)
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctors'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000, null=True, blank=True)
    address = models.TextField(max_length=5000, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    rating = models.PositiveSmallIntegerField(default=3, validators=[
        MaxValueValidator(5),
        MinValueValidator(1),
    ])
    hospital = models.ForeignKey(
        Hospital, related_name='doctor', on_delete=models.CASCADE)
    specialisation = models.ManyToManyField(
        Specialisation, related_name='speciality')

    def __str__(self):
        return self.name or 'No Name'

    def get_url(self):
        return reverse('hospital:doctor-home', args=[self.slug])

    def get_all_spec(self):
        specs = ""
        for spec in self.specialisation.all():
            specs += spec.name + ", "
        return specs[:-2]


class Appointment(models.Model):
    class Meta:
        ordering = ('-start_date',)
        verbose_name = 'Appointment'
        verbose_name_plural = 'Appointments'

    id = models.CharField(unique=True, default=uuid.uuid4,
                          editable=False, max_length=50, primary_key=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True)
    patient = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    start_date = models.DateTimeField(blank=True, null=True,
                                      help_text="You can choose dates from now")
    end_date = models.DateTimeField(blank=True, null=True,
                                    help_text="You can choose appointment "
                                              "duration as maximum of 7 days")
    patients_remarks = models.TextField(blank=True, null=True)
    doctors_remarks = models.TextField(blank=True, null=True)
    approved = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    rejection_cause = models.TextField(max_length=20000, blank=True, null=True)

    def __str__(self):
        return str(self.doctor.name + "-" + self.patient.user.first_name)

    def get_start_date(self):
        return self.start_date.date()

    def get_end_date(self):
        return self.end_date.date()

hospital/forms.py
import datetime
from datetimewidget.widgets import DateTimeWidget
from .models import Appointment, Doctor
from django import forms


class AppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].label = 'Begin time'
        self.fields['end_date'].label = 'End time'
        self.fields['patients_remarks'].label = 'Remarks'

        self.fields['start_date'].widget.attrs.update({
            'class': 'uk-width-auto uk-input'
        })
        self.fields['end_date'].widget.attrs.update({
            'class': 'uk-width-auto uk-input'
        })
        self.fields['patients_remarks'].widget.attrs.update({
            'class': 'uk-width-auto uk-input'
        })

    class Meta:
        model = Appointment
        fields = {'patients_remarks', 'start_date', 'end_date'}
        dateTimeOptions = {
            'autoclose': True,
            'startDate': str(datetime.datetime.today().date()),
            'endDate': str(datetime.datetime.today().date() + datetime.timedelta(1)),
            'format': 'mm/dd/yyyy hh:ii',
        }
        widgets = {
            'start_date': DateTimeWidget(options=dateTimeOptions),
            'end_date': DateTimeWidget(options=dateTimeOptions),
        }


class InviteDocForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(InviteDocForm, self).__init__(*args, **kwargs)
        self.fields['user'].label = 'User'
        self.fields['user'].widget.attrs.update({
            'class': 'uk-width-auto uk-input'
        })

        self.fields['name'].label = 'Name'
        self.fields['name'].widget.attrs.update({
            'class': 'uk-width-auto uk-input'
        })
    class Meta:
        model = Doctor
        fields = {'user', 'name'}

hospital/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from medtour import settings
from hospital.filters import DoctorSpecFilter
from hospital.forms import AppointmentForm
from landing.models import City, Profile
from .models import Hospital, Doctor, Appointment


class AppointmentApprove(View):
    def get(self, request, id):
        appointment = Appointment.objects.get(id=id)
        appointment.approved = True
        appointment.rejected = False
        appointment.save()
        send_approval_mail(appointment)
        return redirect(reverse('home', args=[]))


class AppointmentReject(View):
    def get(self, request, id):
        appointment = Appointment.objects.get(id=id)
        appointment.approved = False
        appointment.rejected = True
        appointment.save()
        return redirect(reverse('home', args=[]))


class HospitalHome(View):
    def get(self, request, slug):
        hospital = get_object_or_404(Hospital, slug=slug)
        specs = hospital.specialisation.all()
        doctors = Doctor.objects.filter(hospital=hospital)
        doctors_filter = DoctorSpecFilter(request.GET, queryset=doctors)
        return render(request, 'hospital/hospital-profile.html', {
            'doctors': doctors,
            'specs': specs,
            'hospital': hospital,
            'filter': doctors_filter
        })


class DoctorHome(View):
    def get(self, request, slug):
        doctor = get_object_or_404(Doctor, slug=slug)
        return render(request, 'hospital/doctor-profile.html', {
            'doctor': doctor,
        })


def send_appointment_mail(doctor, patient):
    patient_name = patient.user.first_name
    subject = '[New] Appointment with {}'.format(patient)
    from_email = settings.EMAIL_HOST_USER
    message = render_to_string('emails/new_appointment.html',)
    plain_msg = strip_tags(message)
    send_mail(subject, plain_msg, from_email, [
        doctor.user.email], html_message=message, fail_silently=True)
    return redirect('home')


def send_approval_mail(appointment):
    patient = appointment.patient.user.first_name
    doctor = appointment.doctor.user.first_name
    subject = '[CONFIRMED] Appointment with {}'.format(doctor)
    from_email = settings.EMAIL_HOST_USER
    message = render_to_string('emails/approved_appointment.html',
                               {'patient': patient, 'doctor': doctor, 'appointment': appointment})
    plain_msg = strip_tags(message)
    send_mail(subject, plain_msg, from_email, [
        appointment.patient.user.email], html_message=message, fail_silently=True)
    return redirect('home')


@login_required
def appoint_doctor(request, slug):
    form = AppointmentForm(request.POST or None)
    if form.is_valid():
        formwa = form.save(commit=False)
        formwa.doctor = Doctor.objects.get(slug=slug)
        formwa.patient = Profile.objects.get(user=request.user)
        form.save()
        send_appointment_mail(formwa.doctor, formwa.patient)
        return redirect('home')
    return render(request, 'hospital/appointment.html', {'form': form})


class HospitalsAll(View):
    def get(self, request, message=None, good_message=None):
        search_box_city_value = None
        if 'q' in request.GET:
            search_box_city_value = request.GET['q']
        hospitals = Hospital.objects.all()
        if search_box_city_value is not None:
            search_box_city_value_trimmed = "".join(
                search_box_city_value.split())
            city_name = search_box_city_value_trimmed.split(',')
            city = get_object_or_404(City, name=city_name[0])
            hospitals = Hospital.objects.filter(user__profile__city=city)
        if not request.user.is_anonymous and not message:
            if not request.user.profile.city:
                message = "Please add city to your profile, for better visibility on platform."
        return render(request, 'hospital/hospital-list.html', {
            'hospitals': hospitals,
            'search_box_city_value': search_box_city_value,
            'message': message,
            'good_message': good_message
        })

    def post(self, request, message=None, good_message=None):
        hospitals = Hospital.objects.all()
        if not request.user.is_anonymous:
            if not request.user.profile.city:
                message = "Please add city to your profile, for better visibility on platform."
        return render(request, 'hospital/hospital-list.html', {
            'hospitals': hospitals,
            'message': message,
            'good_message': good_message
        })

hospital/templates/hospital/appointment.html
{% extends 'landing/base.html' %}
{% load static %}

{% block title %}
    Book an appointment | MedTour
{% endblock %}

{% block body %}
    {{ form.media }}
        <div class="uk-card-hover uk-border-round uk-card-default uk-card-body uk-width-1-2@m uk-margin-top uk-align-center">
             <form enctype="multipart/form-data" class="uk-table-responsive entry-input-form" action="#" method="post" novalidate>
                {% csrf_token %}
                <table class="uk-table">
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field in form %}
                            <tr>
                                <td class="uk-text-bold">{{ field.label }}</td>
                                <td>
                                    {{ field }}
                                    {% if field.help_text %}
                                      <p class="uk-text-warning">{{ field.help_text }}</p>
                                    {% endif %}
                                    {% for error in field.errors %}
                                      <p class="uk-text-danger">{{ error }}</p>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <input class="uk-width-auto uk-button uk-button-primary uk-margin-small uk-align-center uk-border-pill" type="submit" value="Submit" />
            </form>
        </div>
{% endblock %}

hospital/templates/hospital/doctor-profile.html
{% extends 'landing/base.html' %}
{% load static %}

{% block title %}
    Doctor Profile | MedTour
{% endblock %}

{% block body %}
    <div class="uk-container uk-margin-medium-top">
        <div>
            <div class="uk-card uk-card-default uk-grid-collapse uk-child-width-1-2@s uk-margin" uk-grid>
                <div class="uk-card-media-left uk-cover-container uk-width-1-3@s">
                    <div class="uk-inline">
                        <img src="{% static 'images/cover-default.png' %}" alt="" uk-cover>
                        <span class="uk-position-absolute uk-transform-center uk-badge uk-text-bold" style="left: 90%; top: 10%">verified</span>
                        <canvas width="450" height="300"></canvas>
                    </div>
                </div>
                <div>
                    <div class="uk-card-body">
                        <h3 class="uk-card-title">{{ doctor }}</h3>
                        <p>{{ doctor.get_all_spec }}</p>
                        <a class="uk-button uk-button-secondary uk-border-pill" href="{% url 'hospital:appoint-doctor' doctor.slug %}">Book an appointment</a> at
                        <a class="uk-link-muted" href="{{ doctor.hospital.get_url }}">{{ doctor.hospital }}</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div>
            <div class="uk-width-1-1@m uk-margin-medium-top">
                <ul class="uk-child-width-expand uk-width-1-1@l uk-text-center uk-border-rounded uk-subnav uk-subnav-pill uk-margin-auto" uk-switcher="animation: uk-animation-slide-top-small, uk-animation-slide-top-medium; duration: 200;">
                    <li class="uk-active uk-padding-remove uk-text-center"><a href="#">Profile Overview</a></li>
                    <li class="uk-padding-remove-right uk-padding-remove uk-text-center"><a href="#">Photos</a></li>
                    <li class="uk-padding-remove-right uk-padding-remove uk-text-center"><a href="#">Reviews</a></li>
                </ul>
                <ul class="uk-switcher uk-width-1-1@l">
                    <li class="uk-active uk-width-1-1@l uk-padding-remove">
                        <div class="uk-width-1-1">
                            <div class="uk-card uk-card-default uk-card-hover uk-width-1-1 uk-text-center uk-card-body uk-align-center">
                               lu
                            </div>
                        </div>
                    </li>
                    <li class="uk-width-1-1@l uk-padding-remove">
                        <div class="uk-width-1-1">
                            <div class="uk-card uk-card-default uk-card-hover uk-width-1-1 uk-card-body">
                               yu
                            </div>
                        </div>
                    </li>
                    <li class="uk-width-1-1@l uk-padding-remove">
                        <div class="uk-width-1-1">
                            <div class="uk-card uk-card-default uk-card-hover uk-width-1-1 uk-card-body">
                               katon
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div> -->
    </div>
{% endblock %}

hospital/templates/hospital/hospital-list.html
{% extends 'landing/base.html' %}
{% load static %}

{% block title %}
    Hospitals | MedTour
{% endblock %}

{% block body %}
    <div class="uk-container uk-margin-top">
        <div action="/hospital/list/" method="post" class="uk-margin-small uk-grid-match" uk-grid>
            <div class="uk-inline uk-width-3-5@s">
                <input class="uk-input" name="search_box_city" id="search_box_city" type="text" placeholder="Enter your city..." data-suggest-url="{% url 'ajax_autocomplete' %}"
                {% if search_box_city_value %}
                    value="{{ search_box_city_value }}"
                {% endif %}>
            </div>
            <div class="uk-width-1-5@s">
                <a id="hospital-filter-button" class="uk-button uk-border-rounded uk-padding-remove-left uk-padding-remove-right uk-button-secondary" href="#">search <span uk-icon=" icon: search;"></span></a>
            </div>
        </div>
        <div class="uk-child-width-1-4@m uk-grid-small uk-grid-match" uk-grid>
            {% if hospitals %}
                {% for hospital in hospitals %}
                    <div>
                        <div class="uk-card hover-shadow-card uk-card-secondary uk-padding-small uk-border-rounded">
                            <h3 class="uk-card-title"> <a class="uk-link-heading" href="{{ hospital.get_url }}">{{ hospital.name }}</a></h3>
                            <div class="uk-card-body uk-padding-remove">
                                <p>
                                    {% with ''|center:hospital.rating as range %}
                                        {% for _ in range %}
                                            <span
                                                {% if hospital.rating >= 3 %}
                                                    class="uk-text-bold uk-text-success"
                                                {% elif hospital.rating >= 2 and hospital.rating < 3 %}
                                                    class="uk-text-bold uk-text-warning"
                                                {% else %}
                                                    class="uk-text-bold"
                                                {% endif %}

                                                uk-icon="star">
                                            </span>
                                        {% endfor %}
                                    {% endwith %}
                                </p>
                                <div class="closer">
                                    <p><span class="uk-text-bold uk-text-danger uk-margin-small-right" uk-icon="location"></span>{{ hospital.address }}</p>
                                    <div class="uk-margin-small-top uk-padding-remove"><p><strong>City:</strong> {{ hospital.user.profile.city.display_name }}</p></div>
                                </div>
                            </div>
                            <hr>
                            <div class="uk-card-footer uk-padding-remove uk-margin-small-top">
                                {% if hospital.phone_number %}
                                    <p><a href="tel:{{ hospital.phone_number }}" class="uk-icon-button" uk-icon="receiver"></a> {{ hospital.phone_number }}</p>
                                {% endif %}

                                {% if hospital.email %}
                                    <p><a href="mailto:{{ hospital.email }}" class="uk-icon-button" uk-icon="mail"></a> {{ hospital.email }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h2 class="uk-text-center uk-text-danger">No hospitals found</h2>
            {% endif %}
        </div>
    </div>

    <script>
        $("#search_box_city").on('keyup', function(e){
            let value = $(this).val();
            let url = $("#search_box_city").attr("data-suggest-url");
            $.ajax({
                url: url,
                data: {
                  'search': value
                },
                dataType: 'json',
                success: function (data) {
                    var list = data.list;
                    $("#search_box_city").autocomplete({
                        autoFocus: true,
                        source: list,
                        minLength: 1
                    });
                }
            });
        });
        $("#search_box_city").on("keydown",function search(e) {
            if(e.keyCode == 13) {
                if($("#search_box_city").val() != '') {
                    filterHospital();
                }
            }
        });
        $("#hospital-filter-button").click( function() {
            if($("#search_box_city").val() != '') {
                filterHospital();
            }
        });
        function filterHospital() {
            var query_string_city = encodeURI($("#search_box_city").val());
            var url = window.location.origin + '/hospital/list/' + '?q=' + query_string_city;
            window.location.assign(url);
        }
    </script>
{% endblock %}

hospital/templates/hospital/hospital-profile.html
{% extends 'landing/base.html' %}
{% load static %}

{% block title %}
    Hospital Profile | MedTour
{% endblock %}

{% block body %}
    <div class="uk-container">

    <div class="uk-inline">
        <img src="{% static 'images/cover-default.png' %}" alt="" class="hospital-cover">
        <div class="uk-position-bottom uk-overlay uk-overlay-default uk-text-left uk-padding-small">

            <div class="uk-margin-remove" uk-grid>
                <div class="uk-width-1-1">
                    <div class="uk-width-1-1 uk-text-left uk-align-center uk-margin-medium-top uk-margin-auto-bottom">
                        <span class="uk-text-lead uk-text-bold">{{ hospital.name }}</span>
                        <br>
                        <span>
                            {{ hospital.address }}
                        </span>
                        <br>
                        <span class="uk-text-bold">Provides </span>
                        <span>
                            {{ hospital.get_all_spec }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
{#        <span class="uk-text-bold">Filter by Speciality: </span>#}
{#        <select class="uk-select uk-width-auto" id="spec" name="spec_list" onChange="">#}
{#          <option value="" selected="selected">---Select---</option>#}
{#          {% for spec in specs %}#}
{#            <option value="{{spec.id}}">{{spec.name}}</option>#}
{#          {% endfor %}#}
{#        </select>#}

        <form method="get">
            <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
              <span class="uk-text-bold">{{ filter.form.specialisation.label_tag }}</span>
                {% for spec in filter.form.specialisation %}
                  <label>
                    {{ spec.tag }} {{ spec.choice_label }}
                  </label>
                {% endfor %}
            </div>
            <button type="submit" class="uk-button uk-button-secondary uk-border-rounded">Apply filters <span uk-icon="search"></span></button>
        </form>
        <hr>
        <div class="uk-width-1-1" uk-grid>
            {% for doctor in filter.qs %}
                <div class="uk-width-1-2@l">
                    <div class="uk-card uk-card-default uk-border-rounded hover-shadow-card">
                    <div class="uk-card-header">
                        <div class="uk-grid-small uk-flex-middle" uk-grid>
                            <div class="uk-width-auto">
                                <img class="uk-border-circle" width="80" height="80" src="{{ doctor.user.profile.avatar }}">
                            </div>
                            <div class="uk-width-expand">
                                <h3 class="uk-card-title uk-margin-remove-bottom"><a class="uk-link-heading" href="{{ doctor.get_url }}">{{ doctor.name }}</a></h3>
                                <p class="uk-text-meta uk-margin-remove-top">{{ doctor.hospital }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="uk-card-body uk-padding-small">
                        <p><span class="uk-text-bold">Specialisations: </span>{{ doctor.get_all_spec }}
                            <br>
                            <span class="uk-text-bold">Rating: </span>
                            {% with ''|center:doctor.rating as range %}
                                {% for _ in range %}
                                    <span
                                        {% if doctor.rating >= 3 %}
                                            class="uk-text-success"
                                        {% elif doctor.rating >= 2 and doctor.rating < 3 %}
                                            class="uk-text-warning"
                                        {% else %}
                                        {% endif %}
                                        uk-icon="star">
                                    </span>
                                {% endfor %}
                            {% endwith %}
                            <span>(10 Reviews)</span>
                        </p>
                    </div>
                    <div class="uk-card-footer uk-text-button">
                        <a href="{{ doctor.get_url }}" class="uk-button uk-text-bold uk-button-text">Book an appointment</a>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}